name:                advent-calendar
version:             0.1.0.0
github:              "matsubara0507/haskell-advent-calendar-2017"
license:             MIT
author:              "MATSUBARA Nobutada"
copyright:           "2017 MATSUBARA Nobutada"

extra-source-files:
- README.md

ghc-options:
- -Wall

dependencies:
- aeson
- base >= 4.7 && < 5
- extensible
- lens
- text

library:
  source-dirs: src
  dependencies:
  - aeson-pretty
  - constraints
  - data-default
  - http-client
  - scalpel-core
  - shelly
  - string-transform
  - unordered-containers
  - webdriver
  - wreq

executables:
  advent-calendar:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-calendar
    - optparse-applicative
